services:
    umanit.command.create_certificat_command:
        class: Umanit\SamlBundle\Command\CreateCertificatCommand
        arguments:
            - '@umanit_saml.service.configuration_service'
        tags: ['console.command']

    umanit.command.refresh_idp_metadata_command:
        class: Umanit\SamlBundle\Command\RefreshIdpMetadataCommand
        arguments:
            - '@umanit_saml.service.metadata_service'
            - '@umanit_saml.service.configuration_service'
        tags: ['console.command']
