services:
    _defaults:
        autowire: false
        autoconfigure: false

    # Controller
    Umanit\SamlBundle\Controller\RedirectionAction:
        class: Umanit\SamlBundle\Controller\RedirectionAction
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags: ['controller.service_arguments', 'container.service_subscriber']

    # Services
    umanit_saml.service.configuration_service:
        class: Umanit\SamlBundle\Service\ConfigurationService
        arguments:
            - ~
    Umanit\SamlBundle\Service\ConfigurationServiceInterface: '@umanit_saml.service.configuration_service'

    umanit_saml.service.saml_anthn_request_service:
        class: Umanit\SamlBundle\Service\SamlAuthnRequestService
        arguments:
            - '@Umanit\SamlBundle\Service\ConfigurationServiceInterface'
    Umanit\SamlBundle\Service\SamlAuthnRequestServiceInterface: '@umanit_saml.service.saml_anthn_request_service'
