services:
    _defaults:
        autowire: false
        autoconfigure: false

    # Controller
    Umanit\SamlBundle\Controller\MetadataAction:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags: ['controller.service_arguments', 'container.service_subscriber']

    Umanit\SamlBundle\Controller\RedirectAction:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags: ['controller.service_arguments', 'container.service_subscriber']

    Umanit\SamlBundle\Controller\AcsAction:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags: ['controller.service_arguments', 'container.service_subscriber']

    Umanit\SamlBundle\Controller\SloAction:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags: ['controller.service_arguments', 'container.service_subscriber']

    Umanit\SamlBundle\Controller\SsoAction:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags: ['controller.service_arguments', 'container.service_subscriber']

    # Services
    umanit_saml.service.configuration_service:
        class: Umanit\SamlBundle\Service\ConfigurationService
        arguments:
            - ~
    Umanit\SamlBundle\Service\ConfigurationServiceInterface: '@umanit_saml.service.configuration_service'

    umanit_saml.service.metadata_service:
        class: Umanit\SamlBundle\Service\MetadataService
        arguments:
            - '@umanit_saml.service.configuration_service'
            - '@router.default'
            - '@router.default'
            - '@umanit_saml.service.x509_certificat_service'
            - '@http_client'
            - '@cache.app.taggable'
            - '@monolog.logger.umanit_saml'
    Umanit\SamlBundle\Service\MetadataServiceInterface: '@umanit_saml.service.metadata_service'

    umanit_saml.service.saml_response_service:
        class: Umanit\SamlBundle\Service\SamlResponseService
        arguments:
            - '@umanit_saml.service.configuration_service'
            - '@umanit_saml.service.metadata_service'
            - '@umanit_saml.service.x509_certificat_service'
    Umanit\SamlBundle\Service\SamlResponseServiceInterface: '@umanit_saml.service.saml_response_service'

    umanit_saml.service.saml_anthn_request_service:
        class: Umanit\SamlBundle\Service\SamlAuthnRequestService
        arguments:
            - '@Umanit\SamlBundle\Service\ConfigurationServiceInterface'
            - '@umanit_saml.service.metadata_service'
            - '@umanit_saml.service.x509_certificat_service'
            - '@request_stack'
    Umanit\SamlBundle\Service\SamlAuthnRequestServiceInterface: '@umanit_saml.service.saml_anthn_request_service'

    umanit_saml.service.send_message_service:
        class: Umanit\SamlBundle\Service\SendMessageService
        arguments:
            - '@Umanit\SamlBundle\Service\ConfigurationServiceInterface'
    Umanit\SamlBundle\Service\SendMessageServiceInterface: '@umanit_saml.service.send_message_service'

    umanit_saml.service.x509_certificat_service:
        class: Umanit\SamlBundle\Service\X509CertificatService
        arguments:
            - '@Umanit\SamlBundle\Service\ConfigurationServiceInterface'
    Umanit\SamlBundle\Service\X509CertificatServiceInterface: '@umanit_saml.service.x509_certificat_service'

    umanit_saml.service.response_service:
        class: Umanit\SamlBundle\Service\ResponseService
        arguments:
            - '@umanit_saml.service.saml_message_service'
            - '@umanit_saml.validator.response_validator'
    Umanit\SamlBundle\Service\ResponseServiceInterface: '@umanit_saml.service.response_service'

    umanit_saml.service.slo_service:
        class: Umanit\SamlBundle\Service\SloService
        arguments:
            - '@umanit_saml.service.saml_message_service'
    Umanit\SamlBundle\Service\SloServiceInterface: '@umanit_saml.service.slo_service'

    umanit_saml.service.saml_message_service:
        class: Umanit\SamlBundle\Service\SamlMessageService
    Umanit\SamlBundle\Service\SamlMessageServiceInterface: '@umanit_saml.service.saml_message_service'

    umanit_saml.guesser.best_content_type_guesser:
        class: Umanit\SamlBundle\Guesser\BestContentTypeGuesser
    Umanit\SamlBundle\Guesser\BestContentTypeGuesserInterface: '@umanit_saml.guesser.best_content_type_guesser'

    umanit_saml.service.inbound_service:
        class: Umanit\SamlBundle\Service\InboundService
        arguments:
            - '@umanit_saml.service.configuration_service'
            - '@umanit_saml.validator.signature_validator'
            - '@umanit_saml.validator.issuer_validator'
    Umanit\SamlBundle\Service\InboundServiceInterface: '@umanit_saml.service.inbound_service'

    ####################################################################################################################
    # Validator
    ####################################################################################################################
    umanit_saml.validator.time_validator:
        class: Umanit\SamlBundle\Validator\TimeValidator
        arguments:
            - '@light_saml.validator.model.assertion.assertion_time_validator'
            - '@light_saml.provider.time_provider'
    Umanit\SamlBundle\Validator\TimeValidatorInterface: '@umanit_saml.validator.time_validator'

    umanit_saml.validator.signature_validator:
        class: Umanit\SamlBundle\Validator\SignatureValidator
        arguments:
            - '@umanit_saml.service.configuration_service'
            - '@umanit_saml.service.metadata_service'
    Umanit\SamlBundle\Validator\SignatureValidatorInterface: '@umanit_saml.validator.signature_validator'

    umanit_saml.validator.issuer_validator:
        class: Umanit\SamlBundle\Validator\IssuerValidator
        arguments:
            - '@light_saml.validator.model.name_id.name_id_validator'
    Umanit\SamlBundle\Validator\IssuerValidatorInterface: '@umanit_saml.validator.issuer_validator'

    umanit_saml.validator.response_validator:
        class: Umanit\SamlBundle\Validator\ResponseValidator
        arguments:
            - '@umanit_saml.service.configuration_service'
            - '@umanit_saml.service.metadata_service'
            - '@umanit_saml.service.x509_certificat_service'
            - '@cache.app.taggable'
            - '@light_saml.validator.model.assertion.assertion_validator'
            - '@umanit_saml.validator.signature_validator'
            - '@umanit_saml.validator.issuer_validator'
            - '@umanit_saml.validator.time_validator'
            - '@monolog.logger.umanit_saml'
    Umanit\SamlBundle\Validator\ResponseValidatorInterface: '@umanit_saml.validator.response_validator'

    umanit_saml.validator.slo_validator:
        class: Umanit\SamlBundle\Validator\SloValidator
        arguments:
            - '@umanit_saml.service.configuration_service'
            - '@umanit_saml.service.metadata_service'
            - '@umanit_saml.service.x509_certificat_service'
            - '@cache.app.taggable'
            - '@light_saml.validator.model.assertion.assertion_validator'
            - '@umanit_saml.validator.signature_validator'
            - '@umanit_saml.validator.issuer_validator'
            - '@umanit_saml.validator.time_validator'
            - '@monolog.logger.umanit_saml'
    Umanit\SamlBundle\Validator\SloValidatorInterface: '@umanit_saml.validator.slo_validator'

    umanit_saml.security.http.authenticator.saml_authenticator:
        class: Umanit\SamlBundle\Security\Http\Authenticator\SamlAuthenticator
        arguments:
            - '@security.http_utils'
            - !abstract defined in SamlFactory
            - !abstract defined in SamlFactory
            - !abstract defined in SamlFactory
            - []
            - '@umanit_saml.service.configuration_service'
            - '@umanit_saml.service.response_service'
            - '@monolog.logger.umanit_saml'

    umanit_saml.security.user.saml_user_provider:
        class: Umanit\SamlBundle\Security\User\SamlUserProvider

    umanit_saml.security.user.saml_scoped_user_provider:
        class: Umanit\SamlBundle\Security\User\SamlScopedUserProvider

    umanit_saml.serializer.saml_element_serializer:
        class: Umanit\SamlBundle\Serializer\SamlElementSerializer
    Umanit\SamlBundle\Serializer\SamlElementSerializerInterface: '@umanit_saml.serializer.saml_element_serializer'

    umanit_saml.twig.saml_extension:
        class: Umanit\SamlBundle\Twig\SamlExtension
        arguments:
            - '@umanit_saml.service.configuration_service'
            - '@umanit_saml.service.saml_response_service'
            - '@umanit_saml.serializer.saml_element_serializer'
        tags: ['twig.extension']

    umanit_saml.security.http.authentication.saml_authentication_success_handler:
        class: Umanit\SamlBundle\Security\Http\Authentication\SamlAuthenticationSuccessHandler
        arguments:
            - '@security.http_utils'
            - []
            - '@monolog.logger.umanit_saml'

    umanit_saml.security.http.event_subscriber.check_attributes_subscriber:
        class: Umanit\SamlBundle\Security\Http\EventSubscriber\CheckAttributesSubscriber
        tags: ['kernel.event_subscriber']
